# Generated by Django 2.1.4 on 2019-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
