# Generated by Django 2.1.4 on 2018-12-28 10:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_category', models.TextField(null=True)),
                ('role_type', models.TextField(default='Regular User')),
            ],
            options={
                'db_table': 'cn_rise_user',
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
