# Generated by Django 2.1.4 on 2019-03-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.TextField(choices=[('Super Admin', '超级管理员'), ('Regular User', '普通用户')], default='Regular User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.TextField(choices=[('staff', '员工'), ('student', '学生'), ('adjunctProfessor', '兼职教授')], null=True),
        ),
    ]
