# Generated by Django 2.1.4 on 2019-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190305_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.TextField(choices=[('staff', '职工'), ('student', '学生'), ('adjunctProfessor', '兼职教授')], null=True),
        ),
    ]
