# Generated by Django 2.1.4 on 2018-12-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='browseCounts',
            new_name='views_number',
        ),
    ]
