# Generated by Django 2.1.4 on 2019-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_auto_20181229_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='news_id',
            field=models.IntegerField(null=True),
        ),
    ]
