# Generated by Django 2.1.4 on 2019-02-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_exchange_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
    ]
