# Generated by Django 2.1.4 on 2019-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_auto_20190214_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='type',
            field=models.CharField(choices=[('mission', '出访'), ('visitor', '来访')], max_length=10),
        ),
    ]
