# Generated by Django 2.1.4 on 2018-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(null=True)),
                ('browseCounts', models.IntegerField(null=True)),
                ('image', models.TextField(null=True)),
                ('sliderFlag', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cn_rise_conference',
            },
        ),
    ]
