# Generated by Django 2.1.4 on 2019-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_conference_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='type',
            field=models.CharField(choices=[('domestic', '国内'), ('foreign', '国外')], max_length=10),
        ),
    ]
