# Generated by Django 2.1.4 on 2019-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20190305_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
