# Generated by Django 2.1.4 on 2019-02-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='AboutUs',
        ),
    ]
