# Generated by Django 2.1.4 on 2018-12-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
    ]
