# Generated by Django 2.1.4 on 2019-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20181229_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publications',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reports',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
    ]
