# Generated by Django 2.1.4 on 2019-02-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20190214_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='research_category',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='views_number',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='views_number',
        ),
        migrations.AddField(
            model_name='projects',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
