# Generated by Django 2.1.4 on 2019-02-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20190215_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='public_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='public_year',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='report_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='report_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='report_year',
            new_name='year',
        ),
    ]
