# Generated by Django 2.1.4 on 2019-02-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20190215_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='pdf',
            field=models.TextField(null=True),
        ),
    ]
