# Generated by Django 2.1.4 on 2019-02-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_publications_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='pdf',
        ),
    ]
