# Generated by Django 2.1.4 on 2019-03-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20190312_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='other',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='pdf_path',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reports',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='year',
            field=models.TextField(null=True),
        ),
    ]
