# Generated by Django 2.1.4 on 2018-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user_category', models.TextField()),
                ('office', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('profession', models.TextField(null=True)),
                ('position', models.TextField(null=True)),
                ('degree', models.TextField()),
                ('degreeId', models.BigIntegerField()),
                ('professionalTitle', models.TextField()),
                ('area', models.TextField()),
                ('interesting', models.TextField(null=True)),
                ('introduce', models.TextField(null=True)),
                ('project', models.TextField(null=True)),
                ('achievement', models.TextField(null=True)),
                ('activity', models.TextField(null=True)),
                ('papers', models.TextField(null=True)),
                ('report', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('img', models.TextField()),
                ('status', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cn_rise_people',
            },
        ),
    ]
