# Generated by Django 2.1.4 on 2019-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='introduce',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='link',
            new_name='publication',
        ),
        migrations.RemoveField(
            model_name='people',
            name='papers',
        ),
        migrations.RemoveField(
            model_name='people',
            name='profession',
        ),
        migrations.AlterField(
            model_name='people',
            name='area',
            field=models.TextField(null=True),
        ),
    ]
