# Generated by Django 2.1.4 on 2019-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190220_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='degreeId',
            field=models.BigIntegerField(null=True),
        ),
    ]
