# Generated by Django 2.1.4 on 2019-02-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190220_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='degree',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='user_category',
            field=models.TextField(null=True),
        ),
    ]
