# Generated by Django 2.1.4 on 2019-02-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190222_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='enrollmentTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='graduationTime',
            field=models.DateTimeField(null=True),
        ),
    ]
