# Generated by Django 2.1.4 on 2019-02-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190226_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='imgPath',
            field=models.TextField(null=True),
        ),
    ]
