# Generated by Django 2.1.4 on 2019-03-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_people_imgpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjunctProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField(null=True)),
                ('degree', models.TextField(null=True)),
                ('professionalTitle', models.TextField()),
                ('img', models.TextField(null=True)),
                ('imgPath', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('biography', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cn_rise_adjunct_professor',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('office', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('position', models.TextField(null=True)),
                ('degree', models.TextField(null=True)),
                ('professionalTitle', models.TextField()),
                ('profession', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('interesting', models.TextField(null=True)),
                ('biography', models.TextField(null=True)),
                ('project', models.TextField(null=True)),
                ('achievement', models.TextField(null=True)),
                ('activity', models.TextField(null=True)),
                ('publication', models.TextField(null=True)),
                ('report', models.TextField(null=True)),
                ('img', models.TextField(null=True)),
                ('imgPath', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cn_rise_staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField(null=True)),
                ('enrollmentTime', models.DateTimeField(null=True)),
                ('graduationTime', models.DateTimeField(null=True)),
                ('type', models.TextField(null=True)),
                ('status', models.TextField(default='在读', null=True)),
                ('supervisor', models.TextField(default='刘志明教授', null=True)),
                ('supervisorLink', models.TextField(null=True)),
                ('img', models.TextField(null=True)),
                ('imgPath', models.TextField(null=True)),
                ('project', models.TextField(null=True)),
                ('activity', models.TextField(null=True)),
                ('publication', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('biography', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cn_rise_student',
            },
        ),
    ]
