# Generated by Django 2.1.4 on 2019-03-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190301_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='status',
            new_name='graduateStatus',
        ),
    ]
