# Generated by Django 2.1.4 on 2019-03-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20190301_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
