# Generated by Django 2.1.4 on 2019-03-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_delete_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-type']},
        ),
    ]
