# Generated by Django 2.1.4 on 2019-03-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20190304_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['type']},
        ),
    ]
