# Generated by Django 2.1.4 on 2019-03-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20190304_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.BooleanField(choices=[(0, '不在职'), (1, '在职')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduateStatus',
            field=models.TextField(choices=[('postgraduate', '在读'), ('graduate', '毕业')], default='postgraduate', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='supervisor',
            field=models.TextField(choices=[('刘志明', '刘志明教授'), ('赖红', '赖红副教授'), ('叶明', '叶明副教授')], default='刘志明', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.TextField(choices=[('undergraduate', '本科'), ('master', '硕士'), ('doctor', '博士')], null=True),
        ),
    ]
