# Generated by Django 2.1.4 on 2019-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190305_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjunctprofessor',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
