# Generated by Django 2.1.4 on 2019-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20190307_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollmentTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduationTime',
            field=models.DateField(null=True),
        ),
    ]
