# Generated by Django 2.1.4 on 2019-03-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20190308_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollmentTime',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduationTime',
            field=models.TextField(default=None, null=True),
        ),
    ]
