# Generated by Django 2.1.4 on 2019-03-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_remove_student_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['id']},
        ),
    ]
