# Generated by Django 2.1.4 on 2019-04-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20190311_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='linkName',
            field=models.TextField(null=True),
        ),
    ]
