# Generated by Django 2.1.4 on 2019-05-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20190510_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['type', '-name']},
        ),
    ]
