# Generated by Django 2.1.4 on 2019-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_auto_20190515_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduationTime',
            field=models.TextField(default=None, null=True),
        ),
    ]
