# Generated by Django 2.1.4 on 2019-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_auto_20190515_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollmentTime',
            field=models.TextField(default=None, null=True),
        ),
    ]
