# Generated by Django 2.1.4 on 2019-06-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20190515_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduationTime',
            field=models.TextField(default='', null=True),
        ),
    ]
