# Generated by Django 2.1.4 on 2019-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20190624_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduationTime',
            field=models.TextField(default=None, null=True),
        ),
    ]
