# Generated by Django 2.1.4 on 2019-02-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(null=True)),
                ('views_number', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='seminar')),
                ('news_id', models.IntegerField(null=True)),
                ('sliderFlag', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cn_rise_seminars',
            },
        ),
    ]
