# Generated by Django 2.1.4 on 2018-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminars',
            name='browseCounts',
        ),
        migrations.AddField(
            model_name='seminars',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
    ]
