# Generated by Django 2.1.4 on 2019-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_auto_20190214_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminars',
            name='place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seminars',
            name='speaker',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='seminars',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
