# Generated by Django 2.1.4 on 2019-03-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0003_auto_20190226_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminars',
            options={'ordering': ['time']},
        ),
    ]
