# Generated by Django 2.1.4 on 2019-03-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0004_auto_20190312_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminars',
            options={'ordering': ['-time']},
        ),
    ]
