# Generated by Django 2.1.4 on 2019-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190221_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefromdirector',
            name='imagePath',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sliderpicture',
            name='imagePath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='messagefromdirector',
            name='image',
            field=models.ImageField(null=True, upload_to='slider'),
        ),
        migrations.AlterField(
            model_name='sliderpicture',
            name='image',
            field=models.ImageField(upload_to='slider'),
        ),
    ]
