# Generated by Django 2.1.4 on 2019-04-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190401_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderpicture',
            options={},
        ),
    ]
